### ISSUE TITLE
Empty reports for December 2023

### ISSUE THREAD

**Issue by vielmetti** [DFZ-Name-and-Shame/dnas_stats#1]
The last several reports in December 2023 have been empty - looks like an empty file is being checked into the system.

see e.g. https://github.com/DFZ-Name-and-Shame/dnas_stats/commit/459d4b282adfb7596800b79d6f1856768a31d524

**Comment by jwbensley** [comment]
Thanks for the notification @vielmetti, I've been very busy with the day job the last few weeks and had no time for this project (hopefully I will over the Christmas break). I am re-running the analysis now for the past few weeks, all the missing data should appear in the next 24-48 hours.

**Comment by jwbensley** [comment]
All the missing data is now present and everything is running as normal. Closing the issue as resolved.
